### ISSUE TITLE
min-height class (mh*) clashes with horizontal margin class (mh*)

### ISSUE THREAD

**Issue by jakofranko** [joshavanier/macian#1]
Hey I was playing with this today (love this CSS framework btw!) and noticed that those two classes are the same, so giving an element the class `mh5` will give it both `min-height` and `margin-left/margin-right` attributes 😅

**Comment by joshavanier** [comment]
Now that I look at it, the same thing happens with `c-d` which sets `cursor: default` and `color: #ddd` hehe. I will have to rewrite some class naming schemes later today. Thanks for the heads-up :)

**Comment by jakofranko** [comment]
Haha, too funny. Happy to be of service!

**Comment by joshavanier** [comment]
Finally got around to fixing this lol. I need a proper task management system
