### ISSUE TITLE
Add "build" and/or "prepare" script to the package.json

### ISSUE THREAD

**Issue by jakofranko** [joshavanier/macian#3]
A build script would be nice for minifying the source files.

Also, I noticed this just myself the other day: npm uses the "prepare" script automatically right before publishing to the npm registry. Since Macian only publishes the `macian.min.css` to npm, it would be really helpful to auto-build right before publishing.

Is probably as simple as adding `"prepare": "<minify tool>"` to the `"scripts"`.

For reference: https://docs.npmjs.com/misc/scripts#prepublish-and-prepare

**Comment by joshavanier** [comment]
I created a simple build script using `clean-css`. There's still some improvements to be made (media query blocks are being duplicated) but it'll do for now. `npm run build` or `node build.js` to run :)

**Comment by jakofranko** [comment]
Awesome, thanks @joshavanier :D
